<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First National Bank</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
    <h1>First National Bank</h1>
    <strong>Welcome to First National Bank</strong><br>
    <i>Established 2018</i><br><br><br>
</head>
<body>
<!---------- Header ends --------------->